name: Build Aurora Framework

on:
  push:
    branches: [ main ]  # Change this to match your default branch
    paths:
      - 'src/scss/**/*.scss'
      - 'src/js/*.js'
      - 'gulpfile.js'
      - 'package.json'
      - 'package-lock.json'
      - 'dist/**'

# Add this permissions block
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install gulp-cli globally
      run: npm install -g gulp-cli
    
    - name: Run gulp build
      run: gulp build
      
    - name: Verify dist directory
      run: |
        ls -la dist/
        echo "Checking for built files..."
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f dist/*
        git status
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-build Aurora framework assets"
          git push origin main --force
        fi