name: Build Aurora Framework

on:
  push:
    branches: [ main ]  # Change this to match your default branch
    paths:
      - 'src/scss/**/*.scss'
      - 'src/js/*.js'
      - 'gulpfile.js'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'  # Enable npm caching
    
    - name: Verify package.json exists
      run: |
        ls -la
        cat package.json
    
    - name: Install dependencies
      run: npm ci  # Using npm ci instead of npm install for more reliable builds
      
    - name: Run gulp build
      run: npx gulp build
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -f dist/  # Force add the dist directory
        git commit -m "Auto-build Aurora framework assets" || echo "No changes to commit"
        git push origin || echo "No changes to push"