name: Build CSS Framework

on:
  push:
    branches: [ main ]  # Or whatever your default branch name is
    paths:
      - 'src/**/*.scss'  # Only trigger when SCSS files change, adjust as needed
      - 'gulpfile.js'    # Or when gulpfile changes

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Choose your preferred Node version
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci  # Or npm install if you don't have a package-lock.json
    
    - name: Run gulp
      run: npx gulp  # Or specify your specific gulp task if needed
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-build CSS files" && git push)